@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.cleanup.todoc.models.Project#getColor()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.cleanup.todoc.models.Project",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_856774308 { 
   	label=cleanup
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1925994771 { 
   	label=todoc
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1419102573 { 
   	label=TasksAdapter
	labeljust=l
	fillcolor=white
	style=filled
   
   TasksAdapter592173596XXXonBindViewHolder1925136507[
	label="+ onBindViewHolder()"
	style=filled
	fillcolor=white
	tooltip="TasksAdapter

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1646619053 { 
   	label=TodocDatabase
	labeljust=l
	fillcolor=white
	style=filled
   
   TodocDatabase1426069251XXXgetInstance1678783089[
	label="+ getInstance()"
	style=filled
	fillcolor=white
	tooltip="TodocDatabase

null"
	fontcolor=darkgreen
];

TodocDatabase1426069251XXXprepopulateDatabase0[
	label="+ prepopulateDatabase()"
	style=filled
	fillcolor=white
	tooltip="TodocDatabase

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_560272125 { 
   	label=Project
	labeljust=l
	fillcolor=white
	style=filled
   
   Project2050372082XXXgetColor0[
	label="+ getColor()"
	style=filled
	fillcolor=white
	tooltip="Project

&#10;  Returns the hex (ARGB) code of the color associated to the project.&#10; &#10;  @return the hex (ARGB) code of the color associated to the project&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
TasksAdapter592173596XXXonBindViewHolder1925136507 -> Project2050372082XXXgetColor0;
TodocDatabase1426069251XXXgetInstance1678783089 -> TodocDatabase1426069251XXXprepopulateDatabase0;
TodocDatabase1426069251XXXprepopulateDatabase0 -> Project2050372082XXXgetColor0;
    
}
@enduml