@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.cleanup.todoc.database.TaskDao#orderByNewToLast()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.cleanup.todoc.database.TaskDao",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_856774308 { 
   	label=cleanup
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1925994771 { 
   	label=todoc
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1168105629 { 
   	label=TaskDao_Impl
	labeljust=l
	fillcolor=white
	style=filled
   
   TaskDao_Impl1426069251XXXorderByNewToLast0[
	label="+ orderByNewToLast()"
	style=filled
	fillcolor=white
	tooltip="TaskDao_Impl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1325368178 { 
   	label=TestBaseTodoc
	labeljust=l
	fillcolor=white
	style=filled
   
   TestBaseTodoc1258479462XXXtest_recent_comparator0[
	label="+ test_recent_comparator()"
	style=filled
	fillcolor=white
	tooltip="TestBaseTodoc

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1606619991 { 
   	label=TaskDataRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   TaskDataRepository1295645968XXXorderByNewToLast0[
	label="+ orderByNewToLast()"
	style=filled
	fillcolor=white
	tooltip="TaskDataRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2009645033 { 
   	label=MainFragmentViewModel
	labeljust=l
	fillcolor=white
	style=filled
   
   MainFragmentViewModel592173596XXXorderByNewToLast0[
	label="+ orderByNewToLast()"
	style=filled
	fillcolor=white
	tooltip="MainFragmentViewModel

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2144438821 { 
   	label=MainFragment
	labeljust=l
	fillcolor=white
	style=filled
   
   MainFragment592173596XXXupdateTasks0[
	label="+ updateTasks()"
	style=filled
	fillcolor=white
	tooltip="MainFragment

&#10;  Updates the list of tasks in the UI&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_371968062 { 
   	label=TaskDao
	labeljust=l
	fillcolor=white
	style=filled
   
   TaskDao1426069251XXXorderByNewToLast0[
	label="+ orderByNewToLast()"
	style=filled
	fillcolor=white
	tooltip="TaskDao

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
MainFragment592173596XXXupdateTasks0 -> MainFragmentViewModel592173596XXXorderByNewToLast0;
MainFragmentViewModel592173596XXXorderByNewToLast0 -> TaskDataRepository1295645968XXXorderByNewToLast0;
TaskDao1426069251XXXorderByNewToLast0 -> TaskDao_Impl1426069251XXXorderByNewToLast0;
TaskDataRepository1295645968XXXorderByNewToLast0 -> TaskDao1426069251XXXorderByNewToLast0;
TestBaseTodoc1258479462XXXtest_recent_comparator0 -> TaskDao1426069251XXXorderByNewToLast0;
    
}
@enduml